### ISSUE TITLE
WDIO Version 5 currently not supported

### ISSUE THREAD

**Issue by klamping** [QualityOps/wdio-timeline-reporter#9]
Trying to run this reporter in version 5 results in the following error:
```
Stderr:
[0-0] 2019-02-04T21:52:46.786Z ERROR wdio-local-runner: Failed launching test session: TypeError: ReporterClass is not a constructor
    at BaseReporter.initReporter (/Users/klamping/Sites/temp-wdio-reporters/node_modules/@wdio/runner/build/reporter.js:193:14)
    at Array.map (<anonymous>)
    at new BaseReporter (/Users/klamping/Sites/temp-wdio-reporters/node_modules/@wdio/runner/build/reporter.js:34:39)
    at Runner.run (/Users/klamping/Sites/temp-wdio-reporters/node_modules/@wdio/runner/build/index.js:82:21)
    at process.on.m (/Users/klamping/Sites/temp-wdio-reporters/node_modules/@wdio/local-runner/build/run.js:37:20)
    at emitTwo (events.js:131:20)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I'm guessing this reporter needs to be updated to the new way reporters are constructed:
https://webdriver.io/docs/customreporter.html

To recreate: 
1. Get a new v5 test suite up and running
2. Install and include the 'timeline' reporter in the list of reporters
3. Try and run the tests

**Comment by christian-bromann** [comment]
When can we expect support for it?

**Comment by benzaremean** [comment]
@christian-bromann @klamping I have updated reporter to work with v5. Will raise PR in a few days to add to supported list

**Comment by christian-bromann** [comment]
> Will raise PR in a few days to add to supported list

Let me do that for you! Thanks for porting it over 👍
